modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"

[[mods]]
modId="essential_partner_mod"
version="${file.jarVersion}"
displayName="Essential Partner Mod Integration"
displayURL="https://essential.gg/"
description="<replace me>"

[[dependencies.essential_partner_mod]]
modId="forge"
mandatory=true
versionRange="[33,)"
ordering="NONE"
side="BOTH"
